"""Add UniqueConstraint

Revision ID: 0f68216645a9
Revises: 2e57bc16bc77
Create Date: 2025-03-13 16:03:59.517585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f68216645a9'
down_revision: Union[str, None] = '2e57bc16bc77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_url_key', 'news', type_='unique')
    op.create_unique_constraint('pub_date_url_const', 'news', ['pub_date', 'url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pub_date_url_const', 'news', type_='unique')
    op.create_unique_constraint('news_url_key', 'news', ['url'])
    # ### end Alembic commands ###
