"""Add Null value for content col

Revision ID: 2e57bc16bc77
Revises: 02c628997a82
Create Date: 2025-03-13 12:50:58.129420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e57bc16bc77'
down_revision: Union[str, None] = '02c628997a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
